### ISSUE TITLE
"> Subscriptions Pane" feature seems to be not functioning well

### ISSUE THREAD

**Issue by Omksaini2003** [proffapt/own-youtube#7]
Under "left navigation bar", when we on "> Subscriptions Pane", it doesn't seem to be functional. It is not able to remove subscription pane completely.

It was expected that turning this feature on would remove "Subscription pane" completely from sidebar, but it only limits subscription channel to 7-8 and not removes completely.

Normally we would see :
![Screenshot_20221204_225757](https://user-images.githubusercontent.com/113281200/205506271-dc12feb0-dbde-45c0-ae2f-5b4ed6ba39f0.png)

After turning On the feature we can see that:
![Screenshot_20221204_225841](https://user-images.githubusercontent.com/113281200/205506341-2b65c3ee-5bed-48b4-8b1a-a312b7b8336d.png)

only "show more" option is removed, that too of both "saved playlists" and "subscription pane:.

 - OS: Windows 11
 - Browser : Brave

**Comment by proffapt** [comment]
Yes, I am aware of this issue; it's yet another detailed part of https://github.com/proffapt/own-youtube/issues/1 since the YouTube UI drastically updated last time; haven't got time since then to work on this project.

But seeing its popularity for now, I will start implementing the changes soon; and since this project is under KWoC I will wait for contributions from others. And hence will leave this issue to be solved by the students; if left I will deal with it personally after a month.

**Comment by nidz27** [comment]
@proffapt Can you suggest something for this issue? I tried finding some unique id or class for it but similar ones are used for the other features like explore pane and more from youtube pane.

**Comment by proffapt** [comment]
> @proffapt Can you suggest something for this issue? I tried finding some unique id or class for it but similar ones are used for the other features like explore pane and more from youtube pane.

Did you test it again?
Is it still not functioning?

If similar once are used somewhere then separate them out.

And also do create an option for `trending` because that's not here.

**Comment by nidz27** [comment]
Yes,it is still not functioning as it should. Can you tell me how can I separate them? I was thinking of getting the element and adding a new class maybe, but again to get that element I would need it's id or something unique.

**Comment by proffapt** [comment]
Fixed in #17
